export default [
  {
    id: "1",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "2",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "3",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Pranav",
    lastname: "fgd",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
  {
    id: "1",
    firstname: "Akhil",
    lastname: "Kala",
    domains: ["CS", "ELEC", "SM"],
    stream: "ECE",
  },
];
