export default [
  {
    id: 1,
    student: 6,
    reasoning_ans_link: "http://google.com/",
    reasoning_marks: 0,
    cs_ans_link: "http://google.com/",
    cs_ans_marks: 0,
    elec_ans_link: null,
    elec_ans_marks: 0,
    setno: 4,
  },
  {
    id: 2,
    student: 6,
    reasoning_ans_link: "http://google.com/",
    reasoning_marks: 1,
    cs_ans_link: "http://google.com/",
    cs_ans_marks: 2,
    elec_ans_link: "http://google.com/",
    elec_ans_marks: 0,
    setno: 4,
  },
  {
    id: 3,
    student: 6,
    reasoning_ans_link: "http://google.com/",
    reasoning_marks: 0,
    cs_ans_link: "http://google.com/",
    cs_ans_marks: 0,
    elec_ans_link: null,
    elec_ans_marks: 0,
    setno: 4,
  },
];
